spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false
  mvc:
    format:
      date: iso