spring:
  profiles:
    active: qa, local

  datasource:
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: ${datasource.driver-class-name}
  liquibase:
    change-log: db.changelog/db.changelog-master.yaml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  mvc:
    format:
      date: iso

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${oauth2.google.clientId}
            clientSecret: ${oauth2.google.clientSecret}
            redirectUri: ${oauth2.google.redirectUri}
            scope: ${oauth2.google.scope}


springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    url: /v3/api-docs
